version: '3.9'

services:
  leet_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: leet_app
    env_file:
      - .env
    ports:
      - 5050:5050
    restart: always
